### PR TITLE
Update harbour-slideshow-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,
Don't really know what to do with line 51-52. You might want to change source tag?

### CODE REVIEW

**Comment by pinniini** [comment]
Could you please explain what is confusing with those lines? Would you prefer me to use your github username eson57 for the credits rather than your name?

**Comment by eson57** [comment]
No, I prefer my real name, thank you. It's just that I found the same source in all translation files, regardless of language, so I was wondering if I should really translate that, and what about other translators name?

**Comment by pinniini** [comment]
English and finnish translations are made by me and actually there are no german translations. The german translation file comes by default with the Sailfish OS SDK. And yes, you can translate that line.

**Comment by eson57** [comment]
Aha.. I see! Ok, then I'll finish the string. Thanks!

**Pull request merged**
